program: "/content/deep_rppg/main.py"
#program: "main.py"
method: "bayes"
name: "HT_LSTMDFMTM128_RTRPPG_F0"
parameters:
  fold:
    distribution: constant
    value: 0
  epochs:
    distribution: constant
    value: 50      
  loss:
    distribution: categorical
    values: ["NP_NSNR","NP","MSE"]       
  learning_rate:
    distribution: uniform
    max: 0.01
    min: 0.00001   
  lambda_loss:
    distribution: uniform
    max: 3.0
    min: 0.0 
  is_SWEEP:
    distribution: constant
    value: 1
  is_reproducible:
    distribution: constant
    value: 1
  load_dataset_path:
    distribution: constant
    value: /content/drive/MyDrive/Deivid/VIPL/Experiments/RTrPPG
    #value: E:/results/VIPL/Shuffled/UB8/YUV/b8e15_NPNSNR/CV5F
  save_path:
    distribution: constant
    value: E:/results/VIPL/test_dataset
  database_name:
    distribution: constant
    value: VIPL    
  dataset_percentage:
    distribution: constant
    value: 1 
  save_model_each_n_epochs:
    distribution: constant
    value: 0  
  lstm_state:
    distribution: constant
    value: stateful
  optimizer:
    distribution: constant
    value: ADAM
  metric:
    distribution: constant
    value: hrmae
  network:
    distribution: constant
    value: LSTMDFMTM128       
  batch_size:
    distribution: constant
    value: 32 
  window:
    distribution: constant
    value: 128 
  step_tr:
    distribution: constant
    value: 128     
  step_eval:
    distribution: constant
    value: 128      
description: "HT in LSTMDFMTM128 from RTRPPG signals"
metric:
  goal: "minimize"
  name: "val/hrmae"
  target: 0
project: "sweeps"  
#early_terminate:
#  type: hyperband
#  min_iter: 10
#  eta: 2